apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: "{{ .Values.managedIdentity.name }}-binding"
spec: 
  azureIdentity: {{ .Values.managedIdentity.name }}
  selector: {{ .Values.managedIdentity.name }}
